apiVersion: v1
kind: ReplicationController
metadata:
  name: riak
  labels:
    provider: riak
    heritage: helm
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: riak
        image: quay.io/arschles/riak:devel
        env:
        - name:  RIAK_MASTER
          value: "1"
        - name: DEIS_RIAK_CLUSTER_SERVICE_HOST
          value: "nothing" # if RIAK_MASTER is set to 1, this value is ignored
        - name: DEIS_RIAK_CLUSTER_SERVICE_PORT
          value: "1" # if RIAK_MASTER is set to 1, this value is ignored
        ports:
        - containerPort: 8087
        - containerPort: 8098
